# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ADR.gov
description: Interagency Alternative Dispute Resolution Working Group
baseurl: "/adr-test" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: benbalter/retlab

# GitHub information
# This is used for adding an edit this page link to the footer
github:
  organization: brockfanning
  repository: adr-test
  default_branch: master

# Configuration for setting the site width to 100%
# To enable, uncomment the following line
# site_width: wide

# Configuration for Google Analytics, add your UA code here:
# google_analytics_ua: UA-????????-??

# Configuration for DAP, add your agency ID here:
# dap_agency: GSA

# Uncomment to enable AnchorJS functionality on docs layout.
# See https://github.com/bryanbraun/anchorjs for more information.
# anchor_js_targets: [h1, h2, h3, h4, h5, h6]

# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.

search_site_handle: justice-adr

# Configuration for projects and team collections
# See https://jekyllrb.com/docs/collections/ for more information about collections.
# collections:
#   projects:
#     output: true
#   team:
#     output: true

# Compress Sass
sass:
  style: compressed